Repository Codiary-UMC-6th/Frontend-Codiary, pull requests merged in 2024-07, with the labels that each got.

#2 [chore] initial project setting
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/components/Navbar.jsx
  src/index.js
  src/pages/Main.jsx
  src/pages/Profile.jsx
  src/pages/Team.jsx
  src/reportWebVitals.js
  src/setupTests.js
Labels: chore

#4 [documentation] init README.md
  README.md
Labels: documentation

#6 [feature] github test
  src/test.txt
Labels: feature

#10 [chore] zustand, styled-component install
  package-lock.json
  package.json
Labels: chore

#12 [feature] create Navbar, make common color as variable
  package-lock.json
  package.json
  src/assets/symbols_search.svg
  src/assets/symbols_write.svg
  src/common/Color.js
  src/components/Navbar.jsx
  src/components/SearchBox.jsx
  src/components/WriteBtn.jsx
Labels: feature

#14 [feature] create footer
  src/App.css
  src/App.js
  src/common/Color.js
  src/components/Footer.jsx
  src/components/Navbar.jsx
Labels: feature

#18 create main page
  src/common/Color.js
  src/components/Card.jsx
  src/components/CategoryBtn.jsx
  src/components/MockData.js
  src/components/ViewBtn.jsx
  src/pages/Main.jsx
Labels: feature
