Repository Codiary-UMC-6th/Frontend-Codiary, pull requests merged in 2025-01, with the labels that each got.

#115 [Feature] #114 - 로그인 로직 구현
  src/components/login/LoginModal.tsx
  src/components/login/useLoginMutation.ts
  src/components/navbar/Navbar.tsx
  src/shared/api/signin/index.ts
  src/shared/api/signin/type.ts
  src/store/LoginStore.js
Labels: 🌱 Feat, 🚐 정

#118 [feat] main.tsx change
  src/App.js
  src/components/diaryDetails/OtherCards.tsx
  src/components/main/Card.tsx
  src/pages/Main.tsx
  yarn.lock
Labels: 🌱 Feat

#120 [feat] common things
  public/index.html
Labels: 🌱 Feat

#122 [feat] v2 popular, latest post
  src/components/diaryDetails/OtherCards.tsx
  src/components/main/Card.tsx
  src/pages/Main.tsx
  src/shared/api/main/index.ts
  src/shared/api/main/type.ts
Labels: 🌱 Feat

#124 [ Feat] #116 - 로그아웃 및 카카오 로그인 구현
  src/App.js
  src/components/login/LoginModal.tsx
  src/components/login/component/KakaoCallback.tsx
  src/components/login/useLoginMutation.ts
  src/components/navbar/Navbar.tsx
  src/shared/api/generalResponse.ts
  src/shared/api/logout/index.ts
  src/shared/api/logout/type.ts
  src/shared/api/socialLogin/index.ts
  src/shared/api/socialLogin/type.ts
  src/shared/constant/api.ts
  src/store/LoginStore.js
Labels: 🌱 Feat, 🚐 정

#127 [feat] navbar 메뉴 추가
  src/components/navbar/Navbar.tsx
  src/shared/api/main/index.ts
Labels: 🌱 Feat

#129 [feat] diary detail
  src/components/diaryDetails/BookmarkBtn.tsx
  src/components/diaryDetails/FAB.tsx
  src/components/diaryDetails/KebabModal.tsx
  src/components/diaryDetails/ProfileCard.tsx
  src/components/main/Card.tsx
  src/pages/DiaryDetail.css
  src/pages/DiaryDetails.tsx
  src/pages/Example.jsx
  src/pages/Main.tsx
  src/pages/Profile.tsx
  src/shared/api/diaryDetail/index.ts
  src/shared/api/diaryDetail/type.ts
  src/shared/api/profile/index.ts
  src/shared/api/profile/type.ts
Labels: 🌱 Feat, 🚙 영범

#132 [feat] diary detail comment api
  src/components/diaryDetails/OtherCards.tsx
  src/components/diaryDetails/ProfileCard.tsx
  src/components/diaryDetails/comments/CommentBox.tsx
  src/pages/DiaryDetails.tsx
  src/pages/Example.jsx
  src/pages/Main.tsx
  src/shared/api/diaryDetail/index.ts
  src/shared/api/diaryDetail/type.ts
Labels: 🌱 Feat, 🚙 영범

#134 [feat] follow author
  src/components/diaryDetails/FollowBtn.tsx
  src/components/diaryDetails/ProfileCard.tsx
  src/shared/api/diaryDetail/index.ts
  src/shared/api/diaryDetail/type.ts
Labels: 🌱 Feat

#136 [feat] bookmark api
  src/App.js
  src/assets/diaryDetail/icon_bookmark.svg
  src/assets/diaryDetail/icon_bookmark_fill.svg
  src/assets/diaryDetail/icon_share.svg
  src/components/diaryDetails/BookmarkBtn.tsx
  src/components/diaryDetails/FAB.tsx
  src/components/navbar/Navbar.tsx
  src/pages/Main.tsx
  src/shared/api/diaryDetail/index.ts
  src/shared/api/diaryDetail/type.ts
  src/shared/api/main/index.ts
Labels: 🌱 Feat, 🚙 영범

#138 [feat] diary editor
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/Footer.jsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/WriteBtn.jsx
  src/pages/DiaryEditor.tsx
  yarn.lock
Labels: 🌱 Feat, 🚙 영범

#142 [feat] team typescript
  src/components/team/commons/teamInput.tsx
  src/components/team/diaryCard.tsx
  src/components/team/memberAdd.tsx
  src/components/team/teamAdd.tsx
  src/components/team/teamAddUi.tsx
  src/components/team/teamDiary.tsx
  src/components/team/teamEdit.tsx
  src/components/team/teamMember.tsx
  src/components/team/teamProfile.tsx
  src/shared/api/team/type.ts
Labels: 🌱 Feat, 🚌 정후

#147 Feature/146
  package-lock.json
  package.json
  src/App.js
  src/components/modal/AddModal.tsx
  src/components/profile/ModifyProfile.tsx
  src/components/profile/MyDiary.tsx
  src/components/profile/ProfileLink.tsx
  src/components/profile/Techstack.tsx
  src/components/profile/UserInfo.tsx
  src/pages/Profile.tsx
  src/shared/api/profile/index.ts
  src/shared/api/profile/type.ts
  yarn.lock
Labels: 🌱 Feat, 🚕 현서
