Repository Codiary-UMC-6th/Frontend-Codiary, pull requests merged in 2025-02, with the labels that each got.

#151 [feat] bookmark in diary detail page
  src/components/diaryDetails/BookmarkBtn.tsx
  src/components/diaryDetails/FAB.tsx
  src/pages/DiaryDetails.tsx
  src/shared/api/diaryDetail/type.ts
Labels: 🌱 Feat

#153 [feat] deploy setting
  public/_redirects
  src/components/diaryDetails/ProfileCard.tsx
Labels: 🌱 Feat

#157 [feat] comment
  src/components/diaryDetails/BookmarkBtn.tsx
  src/components/diaryDetails/ProfileCard.tsx
  src/components/diaryDetails/ProfileImg.tsx
  src/components/diaryDetails/comments/CommentBox.tsx
  src/components/diaryDetails/comments/ReplyInput.tsx
  src/pages/DiaryDetails.tsx
  src/shared/api/diaryDetail/index.ts
  src/shared/api/diaryDetail/type.ts
Labels: 🌱 Feat, 🚙 영범

#159 [feat] comment 2
  src/components/diaryDetails/comments/CommentBox.tsx
  src/components/diaryDetails/comments/CommentInput.tsx
  src/components/diaryDetails/comments/CommentPage.tsx
  src/pages/DiaryDetails.tsx
  src/shared/api/diaryDetail/index.ts
  src/shared/api/diaryDetail/type.ts
Labels: 🌱 Feat

#161 [feat] comment 3
  src/components/diaryDetails/FollowBtn.tsx
  src/components/diaryDetails/KebabModal.tsx
  src/components/diaryDetails/ProfileCard.tsx
  src/components/diaryDetails/comments/CommentBox.tsx
  src/components/diaryDetails/comments/CommentPage.tsx
  src/components/main/Card.tsx
  src/components/team/teamDiary.tsx
  src/shared/api/diaryDetail/type.ts
  src/shared/api/main/type.ts
Labels: 🌱 Feat, 🚙 영범

#163 [feat] load team list on navbar
  src/components/navbar/Dropdown.tsx
  src/shared/api/navbar/index.ts
  src/shared/api/navbar/type.ts
Labels: 🌱 Feat, 🚙 영범

#165 [Feat] 팀 페이지 api 연결 & 충돌 해결
  src/App.js
  src/components/profile/MyDiary.tsx
  src/components/profile/PagenationBox.tsx
  src/components/profile/UserInfo.tsx
  src/components/signup/component/SignUpInputContainer.tsx
  src/components/signup/component/SignUpInputTitle.tsx
  src/components/team/teamAdd.tsx
  src/components/team/teamAddUi.tsx
  src/components/team/teamDiary.tsx
  src/components/team/teamMember.tsx
  src/components/team/teamProfile.tsx
  src/pages/Team.jsx
  src/pages/Team.tsx
  src/shared/api/profile/index.ts
  src/shared/api/team/index.ts
  src/shared/api/team/type.ts
Labels: 🌱 Feat, 🚕 현서

#176 [feat] editor color
  src/components/diaryEditor/ToolBox.tsx
  src/pages/DiaryEditor.tsx
Labels: 🌱 Feat, 🚙 영범

#178 [feat] editor - multiple blocks
  src/pages/DiaryEditor.tsx
Labels: 🌱 Feat, 🚙 영범

#180 [feat] editor
  src/pages/DiaryEditor.tsx
  src/pages/DiaryRegister.tsx
Labels: 🌱 Feat, 🚙 영범

#184 [feat] editor slash box
  src/assets/diaryEditor/code_icon.svg
  src/assets/diaryEditor/image_icon.svg
  src/components/diaryEditor/SlashBox.tsx
  src/components/diaryEditor/ToolBox.tsx
  src/pages/DiaryEditor.tsx
Labels: 🌱 Feat, 🚙 영범
